[workspace]
resolver = "3"
members = ["fh-app", "fh-config", "fh-ipc", "fh-manifest", "fh-paths", "fh-plugin", "fh-plugins", "fh-service"]

[workspace.package]
version = "0.1.0"
authors = ["Bryan Hyland <bryan.hyland32@gmail.com>"]
edition = "2024"
license = "MIT"

[workspace.dependencies]
fh-config = { path = "./fh-config" }
fh-ipc = { path = "./fh-ipc" }
fh-manifest = { path = "./fh-manifest" }
fh-paths = { path = "./fh-paths" }
fn-plugin = { path = "./fh-plugin" }
fh-plugins = { path = "./fh-plugins" }
fh-service = { path = "./fh-service" }

color-eyre = "0.6"
freedesktop-desktop-entry = "0.8"
ignore = "0.4"
nucleo-matcher = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
toml = "0.9"
tracing = "0.1"
tracing-subscriber = "0.3"
