[package]
name = "pl-app"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "plasma-launcher"
path = "src/main.rs"

[dependencies]
pl-ipc.workspace = true
pl-plugins.workspace = true
pl-service.workspace = true

color-eyre.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
