[package]
name = "fh-plugin"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fh-ipc.workspace = true
fh-paths.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
