[package]
name = "fh-config"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "foothold-config"
path = "src/main.rs"

[dependencies]
fh-paths.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml.workspace = true
