[package]
name = "pl-plugins"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pl-config.workspace = true
pl-ipc.workspace = true
pl-service.workspace = true

freedesktop-desktop-entry.workspace = true
nucleo-matcher.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true
