[package]
name = "fh-plugins"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fh-config.workspace = true
fh-ipc.workspace = true
fh-paths.workspace = true
fh-service.workspace = true
freedesktop-desktop-entry.workspace = true
nucleo-matcher.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true
